### ISSUE TITLE
neural network how to use the mlens

### ISSUE THREAD

**Issue by garboa** [flennerhag/mlens#102]
hello,if the classifier is neural network,and all the structure of networks is same,how to use the mlens, could you please show me the code?Thanks

**Comment by flennerhag** [comment]
Hi there, 

You can add any model, as long as the model class follows Scikit-learn's ``fit`` and ``predict`` API (e.g. Keras estimators are fine). Just add them as you would any other estimator: 

```python
from sklearn.neural_network import MLPClassifier
from mlens.ensemble import SuperLearner

ensemble = SuperLearner()

ensemble.add(MLPClassifier())
```

I'm closing this issue but if you run into trouble feel free to re-open it.
