### ISSUE TITLE
KerasClassifier fitting inconsistency

### ISSUE THREAD

**Issue by samyip123** [flennerhag/mlens#103]
I'm trying to fit a model that includes KerasClassifier as a model in the ensemble. However, the result seems to be inconsistent. I fitted the model for 20 times and the results varies in one of three cases
1. Fitted successfully 
2. InvalidArgumentError: Matrix size-incompatible: In[0]: [10,4], In[1]: [3,12]
3. NotFoundError: PruneForTargets: Some target nodes not found: group_deps 
When the model is correctly fitted, the predict will result in value error
I am currently on the  mmap branch of the bleeding edge build , would that be the problem, thanks for the help!!

INVALID ARGUMENT ERROR

/Users/ivan/anaconda3/lib/python3.6/site-packages/mlens/parallel/learner.py in _fit(self=<mlens.parallel.learner.SubLearner object>, transformers=Pipeline(name='pipeline-8',
     pipeline=[('min...rue, feature_range=(0, 1)))],
     return_y=True))
    174         t0 = time()
    175         if transformers:
    176             xtemp, ytemp = transformers.transform(xtemp, ytemp)
    177 
    178         # Fit estimator
--> 179         self.estimator.fit(xtemp, ytemp)
        self.estimator.fit = <bound method KerasClassifier.fit of <keras.wrappers.scikit_learn.KerasClassifier object>>
        xtemp = array([[0.68571429, 0.5       , 0.83050847, 0.91...0.54285714, 0.3       , 0.69491525, 0.58333333]])
        ytemp =     0
0   2
74  2
[75 rows x 1 columns]
    180         self.fit_time_ = time() - t0
    181 
    182     def _load_preprocess(self, path):
    183         """Load preprocessing pipeline"""
...........................................................................
/Users/ivan/anaconda3/lib/python3.6/site-packages/keras/wrappers/scikit_learn.py in fit(self=<keras.wrappers.scikit_learn.KerasClassifier object>, x=array([[0.68571429, 0.5       , 0.83050847, 0.91...0.54285714, 0.3       , 0.69491525, 0.58333333]]), y=array([[2],
       [2], [2], [1], ...   [0],  [0],   [2],
       [2]]), sample_weight=None, **kwargs={})
    205         else:
    206             raise ValueError('Invalid shape for y: ' + str(y.shape))
    207         self.n_classes_ = len(self.classes_)
    208         if sample_weight is not None:
    209             kwargs['sample_weight'] = sample_weight
--> 210         return super(KerasClassifier, self).fit(x, y, **kwargs)
        self.fit = <bound method KerasClassifier.fit of <keras.wrappers.scikit_learn.KerasClassifier object>>
        x = array([[0.68571429, 0.5       , 0.83050847, 0.91...0.54285714, 0.3       , 0.69491525, 0.58333333]])
        y = array([[2],      [2],       [2],[1],...       [0],      [0],       [2],       [2]])
        kwargs = {}
    211 
    212     def predict(self, x, **kwargs):
    213         """Returns the class predictions for the given test data.
    214 
...........................................................................
/Users/ivan/anaconda3/lib/python3.6/site-packages/keras/wrappers/scikit_learn.py in fit(self=<keras.wrappers.scikit_learn.KerasClassifier object>, x=array([[0.68571429, 0.5       , 0.83050847, 0.91...0.54285714, 0.3       , 0.69491525, 0.58333333]]), y=array([[2],
       [2],       [2],       [1],...      [0],       [0],       [2],       [2]]), **kwargs={})
    147             y = to_categorical(y)
    148 
    149         fit_args = copy.deepcopy(self.filter_sk_params(Sequential.fit))
    150         fit_args.update(kwargs)
    151 
--> 152         history = self.model.fit(x, y, **fit_args)
        history = undefined
        self.model.fit = <bound method Model.fit of <keras.engine.sequential.Sequential object>>
        x = array([[0.68571429, 0.5       , 0.83050847, 0.91...0.54285714, 0.3       , 0.69491525, 0.58333333]])
        y = array([[2],       [2],       [2],       [1],...       [0],       [0],       [2],[2]])
        fit_args = {'batch_size': 10, 'epochs': 5}
    153 
    154         return history
    155 
    156     def filter_sk_params(self, fn, override=None):
...........................................................................
/Users/ivan/anaconda3/lib/python3.6/site-packages/keras/engine/training.py in fit(self=<keras.engine.sequential.Sequential object>, x=[array([[0.68571429, 0.5       , 0.83050847, 0.91...0.54285714, 0.3       , 0.69491525, 0.58333333]])], y=[array([[2],
       [2],       [2],       [1],...[0],       [0],       [2],       [2]])], batch_size=10, epochs=5, verbose=1, callbacks=None, validation_split=0.0, validation_data=None, shuffle=True, class_weight=None, sample_weight=None, initial_epoch=0, steps_per_epoch=None, validation_steps=None, **kwargs={})
   1032                                         val_ins=val_ins,
   1033                                         shuffle=shuffle,
   1034                                         callback_metrics=callback_metrics,
   1035                                         initial_epoch=initial_epoch,
   1036                                         steps_per_epoch=steps_per_epoch,
-> 1037                                         validation_steps=validation_steps)
        validation_steps = None
   1038 
   1039     def evaluate(self, x=None, y=None,
   1040                  batch_size=None,
   1041                  verbose=1,
...........................................................................
/Users/ivan/anaconda3/lib/python3.6/site-packages/keras/engine/training_arrays.py in fit_loop(model=<keras.engine.sequential.Sequential object>, f=<keras.backend.tensorflow_backend.Function object>, ins=[array([[0.68571429, 0.5       , 0.83050847, 0.91...0.54285714, 0.3       , 0.69491525, 0.58333333]]), array([[2],
       [2],       [2],       [1],...       [0],       [0],[2],       [2]]), array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1...      1., 1., 1., 1., 1., 1., 1.], dtype=float32)], out_labels=['loss', 'acc'], batch_size=10, epochs=5, verbose=1, callbacks=<keras.callbacks.CallbackList object>, val_f=None, val_ins=[], shuffle=True, callback_metrics=['loss', 'acc'], initial_epoch=0, steps_per_epoch=None, validation_steps=None)
    194                 batch_logs['size'] = len(batch_ids)
    195                 callbacks.on_batch_begin(batch_index, batch_logs)
    196                 for i in indices_for_conversion_to_dense:
    197                     ins_batch[i] = ins_batch[i].toarray()
    198 
--> 199                 outs = f(ins_batch)
        outs = undefined
        f = <keras.backend.tensorflow_backend.Function object>
        ins_batch = [array([[0.34285714, 0.4       , 0.52542373, 0.5 ...0.8       , 0.7       , 0.86440678, 1.        ]]), array([[1],
       [1],       [0],       [1],...       [2],       [2],[1],       [2]]), array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)]
    200                 outs = to_list(outs)
    201                 for l, o in zip(out_labels, outs):
    202                     batch_logs[l] = o
    203 
...........................................................................
/Users/ivan/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py in __call__(self=<keras.backend.tensorflow_backend.Function object>, inputs=[array([[0.34285714, 0.4       , 0.52542373, 0.5 ...0.8       , 0.7       , 0.86440678, 1.        ]]), array([[1],
       [1],       [0],        [1], ...  [2],[2],[1],[2]]), array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)])
   2661                     raise ValueError(
   2662                         'Feeding from symbolic tensors is not '
   2663                         'supported with sparse inputs.')
   2664                 return self._legacy_call(inputs)
   2665 
-> 2666             return self._call(inputs)
        self._call = <bound method Function._call of <keras.backend.tensorflow_backend.Function object>>
        inputs = [array([[0.34285714, 0.4       , 0.52542373, 0.5 ...0.8       , 0.7       , 0.86440678, 1.        ]]), array([[1],
       [1],      [0],       [1],...       [2],[2],       [1],       [2]]), array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)]
   2667         else:
   2668             if py_any(is_tensor(x) for x in inputs):
   2669                 raise ValueError(
   2670                     'In order to feed symbolic tensors to a Keras model '
...........................................................................
/Users/ivan/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py in _call(self=<keras.backend.tensorflow_backend.Function object>, inputs=[array([[0.34285714, 0.4       , 0.52542373, 0.5 ...0.8       , 0.7       , 0.86440678, 1.        ]]), array([[1],
       [1], [0], … [2], [2],   [1],   [2]]), array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)])
   2631                 session != self._session):
   2632             self._make_callable(feed_arrays,
   2633                                 feed_symbols,
   2634                                 symbol_vals,
   2635                                 session)
-> 2636         fetched = self._callable_fn(*array_vals)
        fetched = undefined
        self._callable_fn = <tensorflow.python.client.session.BaseSession._Callable object>
        array_vals = [array([[0.34285715, 0.4       , 0.5254237 , 0.5 ...       , 0.86440676, 1.        ]], dtype=float32), array([[1.],
       [1.],       [0.],       [1...  [2.],       [1.],       [2.]], dtype=float32), array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)]
   2637         return fetched[:len(self.outputs)]
   2638 
   2639     def _legacy_call(self, inputs):
   2640         if not isinstance(inputs, (list, tuple)):
...........................................................................
/Users/ivan/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py in __call__(self=<tensorflow.python.client.session.BaseSession._Callable object>, *args=(array([[0.34285715, 0.4       , 0.5254237 , 0.5 ...       , 0.86440676, 1.        ]], dtype=float32), array([[1.],
       [1.],      [0.],       [1...  [2.],       [1.],       [2.]], dtype=float32), array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)), **kwargs={})
   1377         run_metadata_ptr = tf_session.TF_NewBuffer() if run_metadata else None
   1378         # TODO(mrry): Switch to raising an exception from the SWIG wrapper.
   1379         with errors.raise_exception_on_not_ok_status() as status:
   1380           ret = tf_session.TF_SessionRunCallable(
   1381               self._session._session, self._handle, args, status,
-> 1382               run_metadata_ptr)
        run_metadata_ptr = None
   1383         if run_metadata:
   1384           proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)
   1385           run_metadata.ParseFromString(compat.as_bytes(proto_data))
   1386       finally:

...........................................................................
/Users/ivan/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py in __exit__(self=<tensorflow.python.framework.errors_impl.raise_exception_on_not_ok_status object>, type_arg=None, value_arg=None, traceback_arg=None)
    514     try:
    515       if c_api.TF_GetCode(self.status.status) != 0:
    516         raise _make_specific_exception(
    517             None, None,
    518             compat.as_text(c_api.TF_Message(self.status.status)),
--> 519             c_api.TF_GetCode(self.status.status))
        self.status.status = undefined
    520     # Delete the underlying status object from memory otherwise it stays alive
    521     # as there is a reference to status from this from the traceback due to
    522     # raise.
    523     finally:

InvalidArgumentError: Matrix size-incompatible: In[0]: [10,4], In[1]: [3,12]
	 [[Node: dense_1/MatMul = MatMul[T=DT_FLOAT, _class=["loc:@training/Adam/gradients/dense_1/MatMul_grad/MatMul_1"], transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_dense_1_input_0_0, dense_1/kernel/read)]]
___________________________________________________________________________

NOT FOUND ERROR 

/Users/ivan/anaconda3/lib/python3.6/site-packages/mlens/parallel/learner.py in _predict(self=<mlens.parallel.learner.SubLearner object>, transformers=Pipeline(name='pipeline-0',
     pipeline=[('min...rue, feature_range=(0, 1)))],
     return_y=True), score_preds=False)
    194         xtemp, ytemp = slice_array(self.in_array, self.targets, self.out_index)
    195         t0 = time()
    196 
    197         if transformers:
    198             xtemp, ytemp = transformers.transform(xtemp, ytemp)
--> 199         predictions = getattr(self.estimator, self.attr)(xtemp)
        predictions = undefined
        self.estimator = <keras.wrappers.scikit_learn.KerasClassifier object>
        self.attr = 'predict_proba'
        xtemp = array([[0.68571429, 0.5       , 0.85964912, 0.91...0.11428571, 0.6       , 0.10526316, 0.04166667]])
    200 
    201         self.pred_time_ = time() - t0
    202 
    203         # Assign predictions to matrix
...........................................................................
/Users/ivan/anaconda3/lib/python3.6/site-packages/keras/wrappers/scikit_learn.py in predict_proba(self=<keras.wrappers.scikit_learn.KerasClassifier object>, x=array([[0.68571429, 0.5       , 0.85964912, 0.91...0.11428571, 0.6       , 0.10526316, 0.04166667]]), **kwargs={'batch_size': 10})
    251                 to match the scikit-learn API,
    252                 will return an array of shape `(n_samples, 2)`
    253                 (instead of `(n_sample, 1)` as in Keras).
    254         """
    255         kwargs = self.filter_sk_params(Sequential.predict_proba, kwargs)
--> 256         probs = self.model.predict(x, **kwargs)
        probs = undefined
        self.model.predict = <bound method Model.predict of <keras.engine.sequential.Sequential object>>
        x = array([[0.68571429, 0.5       , 0.85964912, 0.91...0.11428571, 0.6       , 0.10526316, 0.04166667]])
        kwargs = {'batch_size': 10}
    257 
    258         # check if binary classification
    259         if probs.shape[1] == 1:
    260             # first column is probability of class 0 and second is of class 1
...........................................................................
/Users/ivan/anaconda3/lib/python3.6/site-packages/keras/engine/training.py in predict(self=<keras.engine.sequential.Sequential object>, x=[array([[0.68571429, 0.5       , 0.85964912, 0.91...0.11428571, 0.6       , 0.10526316, 0.04166667]])], batch_size=10, verbose=0, steps=None)
   1162         self._make_predict_function()
   1163         f = self.predict_function
   1164         return training_arrays.predict_loop(self, f, ins,
   1165                                             batch_size=batch_size,
   1166                                             verbose=verbose,
-> 1167                                             steps=steps)
        steps = None
   1168 
   1169     def train_on_batch(self, x, y,
   1170                        sample_weight=None,
   1171                        class_weight=None):
...........................................................................
/Users/ivan/anaconda3/lib/python3.6/site-packages/keras/engine/training_arrays.py in predict_loop(model=<keras.engine.sequential.Sequential object>, f=<keras.backend.tensorflow_backend.Function object>, ins=[array([[0.68571429, 0.5       , 0.85964912, 0.91...0.11428571, 0.6       , 0.10526316, 0.04166667]])], batch_size=10, verbose=0, steps=None)
    289             else:
    290                 ins_batch = slice_arrays(ins, batch_ids)
    291             for i in indices_for_conversion_to_dense:
    292                 ins_batch[i] = ins_batch[i].toarray()
    293 
--> 294             batch_outs = f(ins_batch)
        batch_outs = undefined
        f = <keras.backend.tensorflow_backend.Function object>
        ins_batch = [array([[0.68571429, 0.5       , 0.85964912, 0.91...0.91428571, 0.4       , 0.98245614, 0.83333333]])]
    295             batch_outs = to_list(batch_outs)
    296             if batch_index == 0:
    297                 # Pre-allocate the results arrays.
    298                 for batch_out in batch_outs:
...........................................................................
/Users/ivan/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py in __call__(self=<keras.backend.tensorflow_backend.Function object>, inputs=[array([[0.68571429, 0.5       , 0.85964912, 0.91...0.91428571, 0.4       , 0.98245614, 0.83333333]])])
   2661                     raise ValueError(
   2662                         'Feeding from symbolic tensors is not '
   2663                         'supported with sparse inputs.')
   2664                 return self._legacy_call(inputs)
   2665 
-> 2666             return self._call(inputs)
        self._call = <bound method Function._call of <keras.backend.tensorflow_backend.Function object>>
        inputs = [array([[0.68571429, 0.5       , 0.85964912, 0.91...0.91428571, 0.4       , 0.98245614, 0.83333333]])]
   2667         else:
   2668             if py_any(is_tensor(x) for x in inputs):
   2669                 raise ValueError(
   2670                     'In order to feed symbolic tensors to a Keras model '
...........................................................................
/Users/ivan/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py in _call(self=<keras.backend.tensorflow_backend.Function object>, inputs=[array([[0.68571429, 0.5       , 0.85964912, 0.91...0.91428571, 0.4       , 0.98245614, 0.83333333]])])
   2630                 feed_symbols != self._feed_symbols or
   2631                 session != self._session):
   2632             self._make_callable(feed_arrays,
   2633                                 feed_symbols,
   2634                                 symbol_vals,
-> 2635                                 session)
        session = <tensorflow.python.client.session.Session object>
   2636         fetched = self._callable_fn(*array_vals)
   2637         return fetched[:len(self.outputs)]
   2638 
   2639     def _legacy_call(self, inputs):
...........................................................................
/Users/ivan/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py in _make_callable(self=<keras.backend.tensorflow_backend.Function object>, feed_arrays=[<tf.Tensor 'dense_1_input:0' shape=(?, 4) dtype=float32>], feed_symbols=[], symbol_vals=[], session=<tensorflow.python.client.session.Session object>)
   2582         for x in self.outputs + self.fetches:
   2583             callable_opts.fetch.append(x.name)
   2584         # Handle updates.
   2585         callable_opts.target.append(self.updates_op.name)
   2586         # Create callable.
-> 2587         callable_fn = session._make_callable_from_options(callable_opts)
        callable_fn = undefined
        session._make_callable_from_options = <bound method BaseSession._make_callable_from_op...tensorflow.python.client.session.Session object>>
        callable_opts = feed: "dense_1_input:0"
fetch: "dense_7/Sigmoid:0"
target: "group_deps"

   2588         # Cache parameters corresponding to the generated callable, so that
   2589         # we can detect future mismatches and refresh the callable.
   2590         self._callable_fn = callable_fn
   2591         self._feed_arrays = feed_arrays
.........................................................................
/Users/ivan/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py in _make_callable_from_options(self=<tensorflow.python.client.session.Session object>, callable_options=feed: "dense_1_input:0"
fetch: "dense_7/Sigmoid:0"
target: "group_deps"
)
   1409 
   1410     Returns:
   1411       A handle to the new callable.
   1412     """
   1413     self._extend_graph()
-> 1414     return BaseSession._Callable(self, callable_options)
        self = <tensorflow.python.client.session.Session object>
        callable_options = feed: "dense_1_input:0"
fetch: "dense_7/Sigmoid:0"
target: "group_deps"

   1415 
   1416 
   1417 @tf_export('Session')
   1418 class Session(BaseSession):
...........................................................................
/Users/ivan/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py in __init__(self=<tensorflow.python.client.session.BaseSession._Callable object>, session=<tensorflow.python.client.session.Session object>, callable_options=feed: "dense_1_input:0"
fetch: "dense_7/Sigmoid:0"
target: "group_deps"
)
   1363       options_ptr = tf_session.TF_NewBufferFromString(
   1364           compat.as_bytes(callable_options.SerializeToString()))
   1365       try:
   1366         with errors.raise_exception_on_not_ok_status() as status:
   1367           self._handle = tf_session.TF_SessionMakeCallable(
-> 1368               session._session, options_ptr, status)
        session._session = <Swig Object of type 'TF_Session *'>
        options_ptr = <tensorflow.python.pywrap_tensorflow_internal.TF...ig Object of type 'TF_Buffer *' at 0x12b2a0e40> >
        status = <Swig Object of type 'TF_Status *'>
   1369       finally:
   1370         tf_session.TF_DeleteBuffer(options_ptr)
   1371 
   1372     def __call__(self, *args, **kwargs):
...........................................................................
/Users/ivan/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py in __exit__(self=<tensorflow.python.framework.errors_impl.raise_exception_on_not_ok_status object>, type_arg=None, value_arg=None, traceback_arg=None)
    514     try:
    515       if c_api.TF_GetCode(self.status.status) != 0:
    516         raise _make_specific_exception(
    517             None, None,
    518             compat.as_text(c_api.TF_Message(self.status.status)),
--> 519             c_api.TF_GetCode(self.status.status))
        self.status.status = undefined
    520     # Delete the underlying status object from memory otherwise it stays alive
    521     # as there is a reference to status from this from the traceback due to
    522     # raise.
    523     finally:

NotFoundError: PruneForTargets: Some target nodes not found: group_deps 
___________________________________________________________________________

PREDICT ERROR

...........................................................................
/Users/ivan/anaconda3/lib/python3.6/site-packages/mlens/parallel/learner.py in _predict(self=<mlens.parallel.learner.SubLearner object>, transformers=Pipeline(name='pipeline-1',
     pipeline=[('min...rue, feature_range=(0, 1)))],
     return_y=True), score_preds=False)
    194         xtemp, ytemp = slice_array(self.in_array, self.targets, self.out_index)
    195         t0 = time()
    196 
    197         if transformers:
    198             xtemp, ytemp = transformers.transform(xtemp, ytemp)
--> 199         predictions = getattr(self.estimator, self.attr)(xtemp)
        predictions = undefined
        self.estimator = <keras.wrappers.scikit_learn.KerasClassifier object>
        self.attr = 'predict_proba'
        xtemp = array([[0.17333333, 0.11949686, 0.85      , 0.88...67, 0.19047176, 0.53846154,
        1.        ]])
    200 
    201         self.pred_time_ = time() - t0
    202 
    203         # Assign predictions to matrix

...........................................................................
/Users/ivan/anaconda3/lib/python3.6/site-packages/keras/wrappers/scikit_learn.py in predict_proba(self=<keras.wrappers.scikit_learn.KerasClassifier object>, x=array([[0.17333333, 0.11949686, 0.85      , 0.88...67, 0.19047176, 0.53846154,
        1.        ]]), **kwargs={'batch_size': 10})
    251                 to match the scikit-learn API,
    252                 will return an array of shape `(n_samples, 2)`
    253                 (instead of `(n_sample, 1)` as in Keras).
    254         """
    255         kwargs = self.filter_sk_params(Sequential.predict_proba, kwargs)
--> 256         probs = self.model.predict(x, **kwargs)
        probs = undefined
        self.model.predict = <bound method Model.predict of <keras.engine.sequential.Sequential object>>
        x = array([[0.17333333, 0.11949686, 0.85      , 0.88...67, 0.19047176, 0.53846154,
        1.        ]])
        kwargs = {'batch_size': 10}
    257 
    258         # check if binary classification
    259         if probs.shape[1] == 1:
    260             # first column is probability of class 0 and second is of class 1

...........................................................................
/Users/ivan/anaconda3/lib/python3.6/site-packages/keras/engine/training.py in predict(self=<keras.engine.sequential.Sequential object>, x=[array([[0.17333333, 0.11949686, 0.85      , 0.88...67, 0.19047176, 0.53846154,
        1.        ]])], batch_size=10, verbose=0, steps=None)
   1157         # Prepare inputs, delegate logic to `predict_loop`.
   1158         if self._uses_dynamic_learning_phase():
   1159             ins = x + [0.]
   1160         else:
   1161             ins = x
-> 1162         self._make_predict_function()
        self._make_predict_function = <bound method Model._make_predict_function of <keras.engine.sequential.Sequential object>>
   1163         f = self.predict_function
   1164         return training_arrays.predict_loop(self, f, ins,
   1165                                             batch_size=batch_size,
   1166                                             verbose=verbose,

...........................................................................
/Users/ivan/anaconda3/lib/python3.6/site-packages/keras/engine/training.py in _make_predict_function(self=<keras.engine.sequential.Sequential object>)
    538             kwargs = getattr(self, '_function_kwargs', {})
    539             self.predict_function = K.function(inputs,
    540                                                self.outputs,
    541                                                updates=self.state_updates,
    542                                                name='predict_function',
--> 543                                                **kwargs)
        kwargs = {}
    544 
    545     def _uses_dynamic_learning_phase(self):
    546         return (self.uses_learning_phase and
    547                 not isinstance(K.learning_phase(), int))

...........................................................................
/Users/ivan/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py in function(inputs=[<tf.Tensor 'dense_1_input:0' shape=(?, 6) dtype=float32>], outputs=[<tf.Tensor 'dense_7/Sigmoid:0' shape=(?, 1) dtype=float32>], updates=[], **kwargs={'name': 'predict_function'})
   2690     if kwargs:
   2691         for key in kwargs:
   2692             if not (has_arg(tf.Session.run, key, True) or has_arg(Function.__init__, key, True)):
   2693                 msg = 'Invalid argument "%s" passed to K.function with TensorFlow backend' % key
   2694                 raise ValueError(msg)
-> 2695     return Function(inputs, outputs, updates=updates, **kwargs)
        inputs = [<tf.Tensor 'dense_1_input:0' shape=(?, 6) dtype=float32>]
        outputs = [<tf.Tensor 'dense_7/Sigmoid:0' shape=(?, 1) dtype=float32>]
        updates = []
        kwargs = {'name': 'predict_function'}
   2696 
   2697 
   2698 def gradients(loss, variables):
   2699     """Returns the gradients of `loss` w.r.t. `variables`.

...........................................................................
/Users/ivan/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py in __init__(self=<keras.backend.tensorflow_backend.Function object>, inputs=[<tf.Tensor 'dense_1_input:0' shape=(?, 6) dtype=float32>], outputs=[<tf.Tensor 'dense_7/Sigmoid:0' shape=(?, 1) dtype=float32>], updates=[], name='predict_function', **session_kwargs={})
   2511         if not isinstance(updates, (list, tuple)):
   2512             raise TypeError('`updates` in a TensorFlow backend function '
   2513                             'should be a list or tuple.')
   2514         self.inputs = list(inputs)
   2515         self.outputs = list(outputs)
-> 2516         with tf.control_dependencies(self.outputs):
        self.outputs = [<tf.Tensor 'dense_7/Sigmoid:0' shape=(?, 1) dtype=float32>]
   2517             updates_ops = []
   2518             for update in updates:
   2519                 if isinstance(update, tuple):
   2520                     p, new_p = update

...........................................................................
/Users/ivan/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py in control_dependencies(control_inputs=[<tf.Tensor 'dense_7/Sigmoid:0' shape=(?, 1) dtype=float32>])
   4793       for control in control_inputs:
   4794         if callable(control):
   4795           control()
   4796     return _NullContextmanager()
   4797   else:
-> 4798     return get_default_graph().control_dependencies(control_inputs)
        control_inputs = [<tf.Tensor 'dense_7/Sigmoid:0' shape=(?, 1) dtype=float32>]
   4799 
   4800 
   4801 class _DefaultStack(threading.local):
   4802   """A thread-local stack of objects for providing implicit defaults."""

...........................................................................
/Users/ivan/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py in control_dependencies(self=<tensorflow.python.framework.ops.Graph object>, control_inputs=[<tf.Tensor 'dense_7/Sigmoid:0' shape=(?, 1) dtype=float32>])
   4379     control_ops = []
   4380     current = self._current_control_dependencies()
   4381     for c in control_inputs:
   4382       if isinstance(c, IndexedSlices):
   4383         c = c.op
-> 4384       c = self.as_graph_element(c)
        c = <tf.Tensor 'dense_7/Sigmoid:0' shape=(?, 1) dtype=float32>
        self.as_graph_element = <bound method Graph.as_graph_element of <tensorflow.python.framework.ops.Graph object>>
   4385       if isinstance(c, Tensor):
   4386         c = c.op
   4387       elif not isinstance(c, Operation):
   4388         raise TypeError("Control input must be Operation or Tensor: %s" % c)

...........................................................................
/Users/ivan/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py in as_graph_element(self=<tensorflow.python.framework.ops.Graph object>, obj=<tf.Tensor 'dense_7/Sigmoid:0' shape=(?, 1) dtype=float32>, allow_tensor=True, allow_operation=True)
   3334     """
   3335     if self._finalized:
   3336       return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
   3337 
   3338     with self._lock:
-> 3339       return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
        self._as_graph_element_locked = <bound method Graph._as_graph_element_locked of <tensorflow.python.framework.ops.Graph object>>
        obj = <tf.Tensor 'dense_7/Sigmoid:0' shape=(?, 1) dtype=float32>
        allow_tensor = True
        allow_operation = True
   3340 
   3341   def _as_graph_element_locked(self, obj, allow_tensor, allow_operation):
   3342     """See `Graph.as_graph_element()` for details."""
   3343     # The vast majority of this function is figuring

...........................................................................
/Users/ivan/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py in _as_graph_element_locked(self=<tensorflow.python.framework.ops.Graph object>, obj=<tf.Tensor 'dense_7/Sigmoid:0' shape=(?, 1) dtype=float32>, allow_tensor=True, allow_operation=True)
   3413         raise ValueError(err_msg)
   3414 
   3415     elif isinstance(obj, Tensor) and allow_tensor:
   3416       # Actually obj is just the object it's referring to.
   3417       if obj.graph is not self:
-> 3418         raise ValueError("Tensor %s is not an element of this graph." % obj)
        obj = <tf.Tensor 'dense_7/Sigmoid:0' shape=(?, 1) dtype=float32>
   3419       return obj
   3420     elif isinstance(obj, Operation) and allow_operation:
   3421       # Actually obj is just the object it's referring to.
   3422       if obj.graph is not self:

ValueError: Tensor Tensor("dense_7/Sigmoid:0", shape=(?, 1), dtype=float32) is not an element of this graph.
___________________________________________________________________________

**Comment by flennerhag** [comment]
Running Keras with TensorFlow as the backend is known to cause issues. Switching to Teano should solve the problem (see #97).
