### ISSUE TITLE
Serialization of Ensemble

### ISSUE THREAD

**Issue by Dandelin3** [flennerhag/mlens#111]
Hi,

your Ensemble library looks very promising!
But is there another possibility to serialize an Ensemble model than to Pickle it? A Lot of scikit learn algorithms can create pmml.
Is something similar possible? Pickle has its issues when you try to deserialize to a more recent code version.....

**Comment by flennerhag** [comment]
Hi, 

Sure, it's possible to use something else. That would come with the risk of making the package incompatible with any library that doesn't support that particular method though. As such, it would have to be implemented as an environmental variable. Feel free to come with a suggestion!
