### ISSUE TITLE
Ensemble learner through hill climbing

### ISSUE THREAD

**Issue by flennerhag** [flennerhag/mlens#13]
Suppose: 

1. We initialize an ensemble with some estimators having default settings.
2. Fit and Predict. Compute the training error.
3. Randomly pick new parameter settings.
4. do 2.

set a learning rate `e`.

while error < threshold:
    a. update every parameter `i` with `-(error(n) - error(n-1)) * (param_i(n) - param_i(n-1)) * e`
    b. Fit and Predict. Compute the training error.

Problem.
All parameters changes are directed based on total error score. So if some parameter `a` is on it's way to a good place, but some other parameter throws the scores off, `a` will be thrown off too.

**Comment by gf712** [comment]
I am not sure if this is exactly what you are looking for, but the [optunity](http://optunity.readthedocs.io/en/latest/index.html) library implements a few algorithms for hyper parameter optimisation and the docs have some interesting papers referenced. I am not sure how these would behave in ensemble learning though, I have never tried it out for that purpose!

**Comment by flennerhag** [comment]
@gf712 sorry for the massive delay in the response. Thanks for the reference, it looks interesting! Probably not going to be integrated into the core code, but might be a nice complement for users.
