### ISSUE TITLE
Questions on the meta-learner in Superlearner

### ISSUE THREAD

**Issue by Skonar90** [flennerhag/mlens#131]
I recently started to use your Superlearner with some classifiers in the first layer and then the meta-learner. When I just do the first layer without the meta-learner there are some classifiers which perform way better in comparison to the case of the inclusion of the meta-learner? 

How does the Meta-Learner Layer determine the weights of the previous layer?

Further, when i call the results you report "score-m ....", but which score is meant 
by this? When I calculate the score for the actual scorer i used i get something different?
Thanks

**Comment by flennerhag** [comment]
The meta-learner is fitted using cross-validation, so the performance of the meta-learner depends on what class you are using and how much data you have. The original SuperLearner using a linear regression as the meta-learner. An even simpler method is to use majority voting (linear regression with weights fixed to ``1``). 

when you create the ensemble, you pass in a ``score`` function. ``score-m`` is the mean value of ``score`` over cv-folds.
