### ISSUE TITLE
Serialize mlens superlearner with KerasRegressor inside

### ISSUE THREAD

**Issue by isaienkov** [flennerhag/mlens#133]
Is there any possibility to save superlearner with a KerasRegressor inside it?
When I use ensemble without KerasRegressor it works fine like:
```
import pickle
pickle.dump(model, open(filename, 'wb'))
```
But if we have KerasRegressor in any layer it is not working.

**Comment by flennerhag** [comment]
Hi! This is a problem with TensorFlow not being serializable. It might help if you switch the Keras backend (#97)?
