### ISSUE TITLE
Save / Restore model

### ISSUE THREAD

**Issue by ledlou** [flennerhag/mlens#139]
How can we save fitted model and restore for subsequent tests?

**Comment by canberkboun9** [comment]
hi @ledlou,

did you solve the problem?

**Comment by ledlou** [comment]
> hi @ledlou,
> 
> did you solve the problem?

Yes, I did but honestly I do not even remember what was exactly the problem :) I use mlens models without any issues from that time, except for when there are remaining data with NaN values due to some coding mistake.

**Comment by canberkboun9** [comment]
Sorry, I was referring to saving sub models and not having to train them again during stacking. If this was your problem, I was asking how did you solve it. There is an open issue [here](https://github.com/flennerhag/mlens/issues/137) which includes a possible solution.

**Comment by ledlou** [comment]
No, my original problem was simply about the saving/restoring of the final optimised model. I was quite beginner in those times :) However, the referred topic is also very useful, thank you for that!

**Comment by canberkboun9** [comment]
Oh, I understand. Thank you!
