### ISSUE TITLE
Will the higher layer models see the raw input training data?

### ISSUE THREAD

**Issue by ajing** [flennerhag/mlens#36]
I just wonder whether the Nth layer is built on only the prediction from the models of the (N-1)th layer or it will also use the original raw input data.

**Comment by flennerhag** [comment]
By default, yes. However, you can propagate the input from one layer to the next with the ``propagate_features`` argument when adding a layer. The [tutorial](http://mlens.readthedocs.io/en/latest/ensemble_tutorial.html#propa-tutorial) on propagating features covers the standard use case. 

I'll close this issue but feel free to reopen if you have further questions.
