### ISSUE TITLE
TypeError in Model Selection

### ISSUE THREAD

**Issue by Mikesev** [flennerhag/mlens#41]
Hi again, I'm working through the model selection section and I think I've hit a bug. I'm passing scipy distributions as indicated in the examples, but omitting from below as there's quite a lot.

Truncated Code:

`from mlens.metrics import make_scorer
mae_scorer = make_scorer(mean_absolute_error, greater_is_better=False)

evaluator = Evaluator(mae_scorer, cv=5, random_state=seed, verbose=1)
evaluator.evaluate(X_mean, y, estimators, params, n_iter=10)`

Error:

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-41-e3c13cf31ba8> in <module>()
     65 
     66 evaluator = Evaluator(mae_scorer, cv=5, random_state=seed, verbose=1)
---> 67 evaluator.evaluate(X_mean, y, estimators, params, n_iter=10)

C:\Anaconda2\lib\site-packages\mlens\model_selection\model_selection.pyc in evaluate(self, X, y, estimators, param_dicts, n_iter)
    387         self.estimators = check_instances(estimators)
    388         self.n_iter = n_iter
--> 389         self._param_sets(param_dicts)
    390 
    391         if self.verbose > 0:

C:\Anaconda2\lib\site-packages\mlens\model_selection\model_selection.pyc in _param_sets(self, param_dicts)
    494             # the expected param_dicts key is 'est_name'
    495             for est_name, _ in self.estimators:
--> 496                 self._set_params(param_dicts, est_name)
    497         else:
    498             # Preprocessing

C:\Anaconda2\lib\site-packages\mlens\model_selection\model_selection.pyc in _set_params(self, param_dicts, key)
    478         try:
    479             self.params[key] = \
--> 480                 self._draw_params(param_dicts[key])
    481         except KeyError:
    482             # No param draws desired. Set empty dict.

C:\Anaconda2\lib\site-packages\mlens\model_selection\model_selection.pyc in _draw_params(self, param_dists)
    469             draws = dist.rvs(self.n_iter, random_state=self.random_state)
    470 
--> 471             for i, draw in enumerate(draws):
    472                 param_draws[i][param] = draw
    473 

TypeError: 'int' object is not iterable
`

Looks to me as though `draws = dist.rvs(self.n_iter, random_state=self.random_state)` should be  `draws = dist.rvs(size=self.n_iter, random_state=self.random_state)` ?

**Comment by flennerhag** [comment]
Hi,

Yeah that's the intended behavior. Guess I've only used classes where size is the first positional argument. Feel free to make a pull req with the fix, otherwise I'll make the update later this week.

**Comment by flennerhag** [comment]
Btw in the latest update you can avoid having to set the ``backend`` argument all the time either by setting an ``MLENS_BACKEND`` environmental variable, or start your code with

```
from mlens import config
config.set_backend('threading')
```

**Comment by Mikesev** [comment]
Nice, thanks! I'll try and do a pull request this evening if I get time.

**Comment by flennerhag** [comment]
Patched in 0.1.5.1
