### ISSUE TITLE
[FIX] Shuffle samples between layers

### ISSUE THREAD

**Issue by ajing** [flennerhag/mlens#51]
Will different layers of models share the same split? Or, we need to specify the split.

Thanks

**Comment by flennerhag** [comment]
Data is split sequentially based on the indexing at the start. So in general, they will share the same split (unless the number of folds is varied, but there would still be an overlap). One way around this would be to shuffle the input data between layers.

Currently, if ``shuffle=True``, the input is shuffled at the ensemble level before any calls to the ``ParallelManager``. To prevent sharing splits, shuffling inputs should be performed between layers, so the it needs to be moved in to the ``ParallelManager.process`` method. Shouldn't be too hard though.

**Comment by ajing** [comment]
Thanks for your prompt reply!

**Comment by flennerhag** [comment]
Not so fast :) 

I think it makes sense to shuffle the samples between layers. Let's keep the issue open until implemented.
