### ISSUE TITLE
AttributeError: 'SuperLearner' object has no attribute 'scores_'

### ISSUE THREAD

**Issue by jackmiemie** [flennerhag/mlens#59]
Hi, I have found an issue about SuperLearner.scores_.

I have fitted an SuperLearner ensemble and I wanted to check the CV scores of base learners by typing `pd.DataFrame(ensemble.scores_)`. However, an error occurs: 
`AttributeError: 'SuperLearner' object has no attribute 'scores_'`

This is wired. 1) I have checked my instantiated and fitted `ensemble`. There is indeed no `scores_` attribute. 2) I've never seen this issue before.

(And what make me crushed is that I spent a long time fitting this ensemble, only to found I can't see how my base learners behave...) 

Anyway, here is my code:

```Python
ensemble = SuperLearner(scorer=mean_absolute_error, folds=5, random_state=seed, n_jobs=-1, shuffle=True)

ensemble.add([('et01', ExtraTreesRegressor(n_estimators=..., max_depth=..., n_jobs=-1)),
              ('et02', ExtraTreesRegressor(n_estimators=..., max_depth=..., n_jobs=-1)),
              ('et03', ExtraTreesRegressor(n_estimators=..., max_depth=..., n_jobs=-1)),
              ('xgb01', XGBRegressor(n_estimators=..., max_depth=..., learning_rate=..., nthread=20)),
              ('xgb02', XGBRegressor(n_estimators=..., max_depth=..., learning_rate=..., nthread=20)),
              ('xgb03', XGBRegressor(n_estimators=..., learning_rate=..., max_depth=..., gamma=..., nthread=20)),
              ('rf01', RandomForestRegressor(n_estimators=..., n_jobs=-1)),
              ('rf02', RandomForestRegressor(n_estimators=..., n_jobs=-1)),
              ('rf03', RandomForestRegressor(n_estimators=..., n_jobs=-1)),
              ('ridge01', Ridge(alpha=...)),
              ('ridge02', Ridge(alpha=...)),
              ('ridge03', Ridge(alpha=...)),
              ('lasso01', Lasso(alpha=...)),
              ('lasso02', Lasso(alpha=...)),
              ('lasso03', Lasso(alpha=...)),
              ('lgbm01', LGBMRegressor(n_estimators=..., learning_rate=...)),
              ('lgbm02', LGBMRegressor(n_estimators=..., learning_rate=...)),
              ('lgbm03', LGBMRegressor(n_estimators=..., learning_rate=...)),
              ('mlp01', MLPRegressor(hidden_layer_sizes=(...,))),
              ('mlp02', MLPRegressor(hidden_layer_sizes=(...,)))
             ])

ensemble.add_meta(Ridge(alpha=..., fit_intercept=False))

ensemble.fit(X, y)

print pd.DataFrame(ensemble.scores_)
```

So, my question is:

Q1. Is this the problem of my code or mlens ? I'm using 0.1.6 version

Q2. If this is the problem of my code, where should I change ?

**Comment by flennerhag** [comment]
Your code looks fine. A failed ``fit`` call might not populate the ``scores_`` attribute, but a normal ``fit`` call certainly will. So there really should be a ``scores_`` attribute.

The only thing that would make sense is if you're actually running on the ``0.2.0`` version, which does in fact not have the ``scores_`` attribute, but instead a ``data`` attribute. Could you:

- double check that you are running on version ``0.1.6``? (Do ``import mlens; print(mlens.__version__)``
- if you're not on ``0.1.6`` or lower, check if there's a ``data`` attribute
- if you are on ``0.1.6``, there's something off. The ``scores_`` attribute is unit tested so there's something lurking in the details. Could you provide a minimal working example that raises this error?

**Comment by flennerhag** [comment]
Btw if you're prototyping the ensemble architecture, for large enough datasets (say over 10k samples) it won't that much a difference if you use 2 or 5-fold CV (if you're data is iid). So you can save yourself some time using 2-fold when experimenting, and push up the fold count for the final ensemble.

Also give the ``BlendEnsemble`` or ``Subsemble`` classes a try. They are much faster and for large enough datasets they perform similarly to the Super Learner. The Subsemble can actually do better. 

(final note: if you're running the ensemble with ``n_jobs > 1``,  setting ``n_jobs != 1`` on the base learners won't make a difference, except for the meta layer.)

**Comment by jackmiemie** [comment]
Thank you !

I have double checked my mlens version by `import mlens; print(mlens.__version__)`. It is indeed `0.1.6`. So, I think there might be something off. I'm going to switch to `0.2.0`.

Thank you for your advice. I will try `Subsemble` classes.

**Comment by flennerhag** [comment]
Ok. I don't think the attribute error is a package problem, but it's hard to say why you get it without isolating the cause. You can switch to 0.2.0, just be aware that it's in development still so there might be slight alterations by the time it's released.

**Comment by flennerhag** [comment]
Mute as of #67.
