### ISSUE TITLE
Map different preprocess to estimators

### ISSUE THREAD

**Issue by shuyangdu** [flennerhag/mlens#61]
As mentioned in the doc, we can map different preprocess to different estimators as 
```
preprocessing_cases = {"case-1": [trans_1, trans_2],
                                          "case-2": [alt_trans_1, alt_trans_2]}

estimators = {"case-1": [est_a, est_b],
                       "case-2": [est_c, est_d]}
```

Doing this, do we use trans_1 for est_a and trans_2 for est_b? Then if I use 

```
preprocessing_cases = {"case-1": [trans_1],
                                          "case-2": [alt_trans_1]}

estimators = {"case-1": [est_a, est_b],
                       "case-2": [est_c, est_d]}
```

Does this mean I will use trans_1 for both est_a and est_b while alt_trans_1 for both est_c and est_d?

If the first usage can already handle the mapping between preprocess to estimators in the list, why do we need the dictionary?

**Comment by flennerhag** [comment]
@shuyangdu  no that's not what happens. Think of the list passed in the ``preprocessing_cases`` dict as one transformer (essentially a Scikit-learn pipeline), and all the estimators in the list under the same key in the ``estimators`` dict as all estimators applied to the transformed data.  Essentially like this:

```python
X_tr = X.copy()
for transformer in preprocessing_cases['case-1']:
    X_tr = trans_1.fit_transform(X_tr)

for estimator in estimators['case-1']:
    estimator.fit(X_tr, y)
```

Note that if you only have **one** preprocessing case, you don't need to create a dictionary but can pass the lists directly.

Sorry for the confusion, hope this clarifies.

**Comment by shuyangdu** [comment]
Thank you for your reply! So to verify, the list for preprocessing and estimators have different meanings. The list for peprocessing is for 'sequentially' preprocess data. But the list for estimators is just a set of estimators. The order in preprocessing list matters while the order in estimator list not.

**Comment by flennerhag** [comment]
Happy to help, and yes that's right!
