### ISSUE TITLE
Does weight supported in mlen for training?

### ISSUE THREAD

**Issue by chenwangliangguo** [flennerhag/mlens#62]
When training a model, how to use sample_weight? I haven't seen weight parameter in fit function.

**Comment by flennerhag** [comment]
``sample_weight`` is currently not a supported parameter. What did you have in mind?

**Comment by chenwangliangguo** [comment]
I think there could be training parameter sent into base models, keep it same with scikit-learn fit method.

**Comment by flennerhag** [comment]
Sorry for not getting back on this. Somewhat overdue but if you want a linear combination of base models, the best approach is to use a linear model as your meta learner. If you want to fix the weights apriori, you can easily achieve this by writing a dummy estimator class.

**Comment by marty90** [comment]
+1
