### ISSUE TITLE
Improve search engine visibility

### ISSUE THREAD

**Issue by JoshuaC3** [flennerhag/mlens#68]
This seems irrelevant, but I think this is a great package and should have way more interest surrounding it. One of the reasons it might get looked over is that it doesn't appear in searches on google or on github when you search for `stack` or `stacking`, where as some other ensembling/stacking packages do!

Maybe adding this key search word to the readme and the docs would help :) Hopefully this is a useful suggestion.

FYI, I noticed this whilst looking for other package to benchmarking mlens against.

**Comment by flennerhag** [comment]
@JoshuaC3 I think that's a great suggestion! I just added ``stack`` and ``stacking`` as keywords for the repo.

Would you be able to a few key search words in the README?

If you're up for it, would also be great to put some on the [official website landing page](https://github.com/ml-ensemble/ml-ensemble.github.io) and the [info index page](https://github.com/ml-ensemble/ml-ensemble.github.io/blob/master/info/source/index.rst).

**Comment by JoshuaC3** [comment]
Happy to edit the README. I will take a look at the other two and see if I am up to it! I will let you know how I get on.

**Comment by flennerhag** [comment]
@JoshuaC3 any progress? : )
