### ISSUE TITLE
[BUG] Printing evaluator results on WIN with Py 2.7 fails for ``str`` keys. 

### ISSUE THREAD

**Issue by LukasMosser** [flennerhag/mlens#78]
When running the start.py jupyter notebook, codeblock 11 fails with 
`
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-11-95af26c98351> in <module>()
----> 1 print(evaluator.results.keys)
      2 print("Score comparison with best params founds:\n\n%r" % evaluator.results)

C:\Users\sguest\Anaconda2\lib\site-packages\mlens-0.2.1-py2.7.egg\mlens\metrics\utils.pyc in __repr__(self)
     92 
     93     def __repr__(self):
---> 94         return assemble_table(self, self.__padding__, self.__decimals__)
     95 
     96 

C:\Users\sguest\Anaconda2\lib\site-packages\mlens-0.2.1-py2.7.egg\mlens\metrics\utils.pyc in assemble_table(data, padding, decimals)
    138                 continue
    139 
--> 140             v_ = len(_get_string(v, decimals))
    141             if v_ > max_col_len[key]:
    142                 max_col_len[key] = v_

C:\Users\sguest\Anaconda2\lib\site-packages\mlens-0.2.1-py2.7.egg\mlens\metrics\utils.pyc in _get_string(obj, dec)
     22     """Stringify object"""
     23     try:
---> 24         return '{0:.{dec}f}'.format(obj, dec=dec)
     25     except TypeError:
     26         return obj.__str__()

ValueError: Unknown format code 'f' for object of type 'str'`

**Comment by flennerhag** [comment]
@LukasMosser by the looks of it, your running Python 2.7 on Windows, which is the platform combination with lowest support, so this is a minor bug that slipped through the unit tests. The exception block (line 25) only captures ``TypeError``s, but on Windows with Python 2.7 the error type to capture is ``ValueError``. 

Easily fixed, until then just ignore this error.

**Comment by LukasMosser** [comment]
It's not my preferred platform of choice either :) thanks for the update

**Comment by flennerhag** [comment]
Fixed as of #80.
