### ISSUE TITLE
Errors in documentation 

### ISSUE THREAD

**Issue by howardbandy** [flennerhag/mlens#85]
I am running the Anaconda release of python 3.6 under Windows 10.  Anaconda does not yet have an mlens package.  The installation instructions given on the ml-ens website (http://ml-ensemble.com/) suggest the command to install mlens is
pip install -U mlens
That causes Anaconda to issue several error messages and installation fails.
The links from ml-ensemble.com to MIT license and to Installation Details both result in 404 errors.

The command  
pip install mlens
does sucessfully install mlens in the Anaconda environment.

**Comment by flennerhag** [comment]
Thanks for notifying! 

``pip install -U`` will package dependencies: the errors you saw were most likely due to failures in updating numpy and scipy. As you point out, mlens doesn't need the latest versions so ``pip install`` should do fine.
