### ISSUE TITLE
Does it support different (multi-view) data input?

### ISSUE THREAD

**Issue by sunjc73** [flennerhag/mlens#92]
In multi-view learning situation, we have multiple feature sets for one object. For instance, for images and videos, color information and texture information are two different kinds of features, which can be regarded as two-view data. So, can mlens accept the input of this different data? That is to say, we would like to use SVM for color feature and KNN for texture information.

**Comment by flennerhag** [comment]
If you can put the features into a 2-D matrix, then it’s easy, just use the [Subset](http://ml-ensemble.com/docs/preprocessing.html) transformer as a preprocessing pipeline to select what columns to train each (or a subset of) base learner(s) on. 

If not, you can try writing your ow preprocessing class, or use the low-level API (see tutorials) to custom design the ensemble architecture.
