### ISSUE TITLE
scoring function support

### ISSUE THREAD

**Issue by 26345211** [flennerhag/mlens#96]
Does the scoring function support an extra vector as input
ie A custom scoring function that takes (predicted_Y, true_Y, weight)
which the weight is used to calculate the final float score

**Comment by flennerhag** [comment]
The scoring function does not support a third input. If this third input is fixed (say constant weights), you can wrap your scoring function: 

```python
def my_scorer(p, y):
    return original_scorer(p, y, w)
```

Note that you can also use this approach if the weights can be inferred from the labels:

```python
def my_scorer(p, y):
    w = get_weights(y)
    return original_scorer(p, y, w)
```
